name: BuildTest

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build Odin (Windows)
        shell: cmd
        run:  |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          ./build.bat
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: odin-windows
          path: odin.exe
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-17 clang-17
      
      - name: Build
        run: |
          chmod +x build_odin.sh
          LLVM_CONFIG=llvm-config-17 ./build_odin.sh debug